# Generated by Django 5.2.8 on 2025-11-15 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companyusers', '0002_alter_companyuser_company_alter_companyuser_user'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('quantity', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('companyuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inflows', to='companyusers.companyuser')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inflows', to='products.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
