# Generated by Django 5.2.8 on 2025-11-15 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands', '0002_brand_delete_brands'),
        ('companyusers', '0002_alter_companyuser_company_alter_companyuser_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='brands.brand')),
                ('companyuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='companyusers.companyuser')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
